### ISSUE TITLE
Getting `ambiguous use of 'makeIterator()'` error when building package with Xcode 14

### ISSUE THREAD

**Issue by ianclawson** [SwifterSwift/SwifterSwift#1042] opened 2022-08-31 04:03 UTC
**Describe the bug**
The package will fail to build and install when used inside a project being compiled on Xcode 14 beta, with an `ambiguous use of 'makeIterator()'` error.

**To Reproduce**
1. Add SwifterSwift as a package inside an iOS project.
2. Open project in Xcode 14 beta.
3. Attempt to build app.

**Expected behavior**
The SwifterSwift package will not fail to build when using Xcode 14 beta.

**Additional context**

Here's a screenshot of the error:
<img width="474" alt="Screen Shot 2022-08-31 at 10 07 12 AM" src="https://user-images.githubusercontent.com/18663382/187726297-0ca877c7-a0e8-401f-a6ff-98dd4a574bb1.png">

I'm about to open a PR which addresses this issue!

- [x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

**Comment by ianclawson** [comment] 2022-08-31 16:09
I just updated the description with the text error and a screenshot in addition to the title for more context. 🙏

**Comment by ianclawson** [comment] 2022-08-31 16:10
Also here's my PR solution: https://github.com/SwifterSwift/SwifterSwift/pull/1043

**Comment by LucianoPAlmeida** [comment] 2022-09-01 12:43
The error is saying which overloads of `makeIterator()` are ambiguous? I'm just curious to know because the fix would be try to disambiguate this a compile time ... I guess

**Comment by theedov** [comment] 2022-09-05 22:58
Any news on this?

**Comment by LucianoPAlmeida** [comment] 2022-09-06 01:22
> Any news on this?

Sorry, I wasn't able to download the beta as I wanted to understand better the issue before reviewing the PR.

**Comment by ianclawson** [comment] 2022-09-06 01:40
I'm currently out of town and can't followup at the moment, unfortunately. I don't recall which two overloads of `makeIterator()` are ambiguous.

Anyone with the beta should be able to pull up the same error though, if someone wanted to look into if before I'm back next week.

**Comment by theedov** [comment] 2022-09-06 01:59
Does this help? 

<img width="982" alt="Screenshot 2022-09-06 at 11 58 06 am" src="https://user-images.githubusercontent.com/30866972/188531100-5d037d93-f773-44fe-8fe1-2e7a447d6fb5.png">

**Comment by LucianoPAlmeida** [comment] 2022-09-06 03:09
Yes a little bit, in the sense that I guess `for byte: UInt8 in self {`would disambiguate that call. Can you give that a shot and confirm if that works? If it does, change the PR to that? 
I'm still not sure how that is ambiguous since the one on Disgest should be an specialization on Sequence... so that is confusing.

**Comment by theedov** [comment] 2022-09-06 03:12
> Yes a little bit, in the sense that I guess `for byte: UInt8 in self {`would disambiguate that call. Can you give that a shot and confirm if that works? If it does, change the PR to that?
> I'm still not sure how that is ambiguous since the one on Disgest should be an specialization on Sequence... so that is confusing.

Just tried it, doesn't work.

**Comment by LucianoPAlmeida** [comment] 2022-09-06 03:22
How about that `for elt in self.makeIterator()`? 
I just found out that this is a compiler regression bug

**Comment by LucianoPAlmeida** [comment] 2022-09-06 03:43
This is the reduced reproducer:
```swift 
struct S: Sequence {
  private var _storage: [UInt8] = []
  func makeIterator() -> Array<UInt8>.Iterator {
    _storage.makeIterator()
  }
  
  typealias Element = UInt8
  class Iterator: IteratorProtocol {
    func next() -> UInt8? { 0 }
    typealias Element = UInt8
  }

  func makeIterator() -> Iterator {
    Iterator()
  }
}
extension S {
  func f() {
    for elt in self { //  error: ambiguous use of 'makeIterator()'
      print(elt)
    }
  }
}
```
I've already reported the bug on https://github.com/apple/swift/issues/

**Comment by theedov** [comment] 2022-09-06 04:31
> How about that `for elt in self.makeIterator()`?
> I just found out that this is a compiler regression bug

Yeah, that works.

**Comment by LucianoPAlmeida** [comment] 2022-09-06 04:33
Nice, for the reference this is the bug: https://github.com/apple/swift/issues/60958 
But I guess we can have this as a work around for now =]

**Comment by theedov** [comment] 2022-09-06 04:56
> Nice, for the reference this is the bug: [apple/swift#60958](https://github.com/apple/swift/issues/60958)
> But I guess we can have this as a work around for now =]

Created a PR for this one. 
https://github.com/SwifterSwift/SwifterSwift/pull/1045

**Comment by LucianoPAlmeida** [comment] 2022-09-06 05:09
Workaround changes landed! Was actually an interesting compiler bug finding
Thank you @ianclawson @theedov

**Closed** 2022-09-06 05:10 UTC
Labels: possible bug
