### ISSUE TITLE
shadowOffset for UILabel is conflict with UILabel's property.

### ISSUE THREAD

**Issue by mlight3** [SwifterSwift/SwifterSwift#622] opened 2019-01-07 03:26 UTC
[v] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
Set shadowOffset, shadowColor, shadowRadius inspectable value on UILabel.

### What did you expect to happen?
UILabel with proper shadow

### What happened instead?
`shadowOffset` is not applied, because UILabel has `shadowOffset` property.
So shadow is always above text, because `layer.shadowOffset` default value is (0, -3)
(Also UILabel has `shadowColor` property.)

### SwifterSwift Environment

- SwifterSwift version: 4.6.0
- Xcode version: 10
- macOS version running Xcode: 10.14.2
- Swift version: 4.2
- Platform(s) running SwifterSwift: iOS

### Demo Project
>Please link to or upload a project we can download that reproduces the issue.

**Comment by multinerd** [comment] 2020-08-10 19:51
Not stale, issue still exists.


```swift
        navBarTitle = UILabel()
        navBarTitle.backgroundColor = .clear
        if let color = navigationController?.navigationBar.titleTextAttributes?[.foregroundColor] as? UIColor {
            navBarTitle.textColor = color
        } else {
            navBarTitle.textColor = self.titleColor
        }
        navBarTitle.shadowOffset = CGSize(width: 0, height: 1);             <---- error here
        navBarTitle.font = UIFont(name: "Roboto-Medium", size: 17.0)
        navBarTitle.textAlignment = .center
        navigationItem.titleView = navBarTitle;
```

> Ambiguous use of 'shadowOffset'


SwifterSwift Environment

-    SwifterSwift version: 5.2.0
-    Xcode version: 11, 12b4
-    macOS version running Xcode: 11b4
-    Swift version: 5.x
-    Platform(s) running SwifterSwift: iOS

**Comment by multinerd** [comment] 2020-08-10 19:57
Whats interesting is that the Xcode says it found 2 candidate, however the first candidate takes me nowhere and the second candidate takes me to this line of code. Note: its a `UIView` extension, not a `UILabel` extension, and `UILabel` inherits `UIView`. 

https://github.com/SwifterSwift/SwifterSwift/blob/master/Sources/SwifterSwift/UIKit/UIViewExtensions.swift#L144

**Comment by LucianoPAlmeida** [comment] 2020-08-10 23:49
Ah sorry, we let the bot close this one... Thanks for reopening this @multinerd 
I think the simplest solution to this is to rename our `UIView` extension to something else, not really sure, but maybe `viewShadowOffset`? Because I honestly don't know if it is possible to disambiguate that at the call

**Comment by Jayxiang** [comment] 2020-08-12 09:21
I think we can add `UILabel` extension `viewShadowColor`,not rename `UIView`, but it is not possible to disambiguate that at the `UILabel`.
And we need to pay attention when using it on Storyboard.

Of course if we rename our `UIView` extension, the previously set `shadowColor` will be retained in `User Defined Runtime Attributes`, so we must reset the view, delete `shadowColor` and add `viewShadowColor`

**Comment by LucianoPAlmeida** [comment] 2020-08-16 22:32
@Jayxiang sorry, the issue is with `shadowColor` or `shadowOffset`? 
I this case I think we can't do anything on UILabel because `shadowOffset` is defined on `UIKit` as seemed in the ambiguous note `1. Found this candidate (UIKit.UILabel)` as ours is `Found this candidate (SwifterSwift.UIView)` so we have to rename the UIView from SwifterSwift, since I can't think any other way to disambiguate this

**Comment by Jayxiang** [comment] 2020-08-17 05:33
@LucianoPAlmeida  yes, only `shadowColor` and `shadowOffset` have the same names as `UILabel`. Maybe we don’t need to make any changes, just add a note to `shadowColor` and `shadowOffset`:
e.g.
-Note: This property does not work in UILabel, you can use `label.layer.shadowColor`

**Comment by LucianoPAlmeida** [comment] 2020-08-17 23:35
@Jayxiang I think that still doesn't solve the problem because people who install `SwifterSwift` remain unable to use a native `UILabel` property, which is not ideal. IMHO I think those kinds of extensions could be deprecated then removed since the abstract simply one level access (from `view.layer.property` to `view.property`) but seems like the more used for people is the IBOutlet and the ability to change this on storyboard ... so in reality, we can't really remove then. The thing is rename seemed like the ideal although it could cause issues with people using it in storyboard.

**Comment by Jayxiang** [comment] 2020-08-18 02:45
@LucianoPAlmeida After I tested it was not the case. The issue is: SwifterSwift's `shadowOffset` and `shadowColor` do not work on `UILabel`,  we can use a native `UILabel` property.

Test：
normal label:
<img width="103" alt="testLabel" src="https://user-images.githubusercontent.com/12928482/90463135-c5bce600-e13c-11ea-83a1-2df986adec85.png">

```
        testLabel.shadowOffset = CGSize(width: 0, height: 4)
        testLabel.shadowColor = .blue
```
<img width="107" alt="set" src="https://user-images.githubusercontent.com/12928482/90463203-eb49ef80-e13c-11ea-9b50-4e7ac299e639.png">

```
        testLabel.shadowOpacity = 1
        testLabel.layer.shadowOffset = CGSize(width: 0, height: 4)
        testLabel.layer.shadowColor = UIColor.red.cgColor
```
<img width="105" alt="set2" src="https://user-images.githubusercontent.com/12928482/90463309-2c420400-e13d-11ea-9d2f-1faceac02e3b.png">

```
 testLabel.backgroundColor = .lightGray
```

<img width="104" alt="set3" src="https://user-images.githubusercontent.com/12928482/90463351-54316780-e13d-11ea-89e4-9fea2ca66137.png">

```
        testLabel.shadowOffset = CGSize(width: 0, height: 4)
        testLabel.shadowColor = .blue

        testLabel.backgroundColor = .lightGray
        testLabel.shadowOpacity = 1
        testLabel.layer.shadowOffset = CGSize(width: 0, height: 4)
        testLabel.layer.shadowColor = UIColor.red.cgColor
```
<img width="113" alt="set4" src="https://user-images.githubusercontent.com/12928482/90463397-75925380-e13d-11ea-9570-ca3af6ecfacc.png">

so this issue only `shadowColor` and `shadowOffset` have the same names as `UILabel`, even if people who install SwifterSwift remain can to use a native UILabel property, so I think the simplest solution to this is just add a note...

**Comment by LucianoPAlmeida** [comment] 2020-08-18 02:58
Hey @Jayxiang, thanks for doing those tests :) 

So trying to use this `testLabel.shadowOffset` doesn't give an ambiguous error? That is the problem I was mentioning (not the fact of the property having the expected visual effect). Users aren't able to access this native UILabel property without ambiguous error.

**Comment by Jayxiang** [comment] 2020-08-18 03:41
@LucianoPAlmeida I use this `testLabel.shadowOffset` doesn't give any errors. 

SwifterSwift Environment

- SwifterSwift version: 5.2.0
- Xcode version: 11.6 (11E708)
- macOS version running Xcode: 11.6 (11E708)
- Swift version: 5.x
- Platform(s) running SwifterSwift: iOS

@multinerd Is it the reason for Xcode? Are you sure there is an error？

**Comment by multinerd** [comment] 2020-08-18 15:11
I am definitely getting an ambiguous error. I created a sample project that reproduces the error, hopefully that will help.

https://github.com/multinerd/SwifterSwift-Bug

**Comment by LucianoPAlmeida** [comment] 2020-08-19 01:21
@Jayxiang Did you explicit import SwifterSwift? Because to me, the ambiguous error is the expected behavior as there's currently no way the compiler can select an overload from that member.
I'm getting the same error on Xcode 12 Beta 1

**Comment by guykogus** [comment] 2020-08-19 09:53
I'm doing the same as @Jayxiang and getting no compiler or visual errors. I'm also on the latest Xcode, so perhaps it was an issue fixed in later versions of the Swift compiler?

**Comment by guykogus** [comment] 2020-08-19 09:54
I tried both with copy-pasting the `UIView` extension code directly into my project and including SwifterSwift as a pod dependency. Same result each time.

**Comment by multinerd** [comment] 2020-08-19 14:03
@guykogus Does this compile for you?

https://github.com/multinerd/SwifterSwift-Bug

**Comment by guykogus** [comment] 2020-08-19 15:12
> @guykogus Does this compile for you?
> 
> https://github.com/multinerd/SwifterSwift-Bug

Yes, but I had to convert it for Xcode 11.6. I'd need to download Xcode 12 beta to test it properly. Maybe that's the issue?

**Comment by multinerd** [comment] 2020-08-20 16:43
@guykogus I could have sworn I had the issue with xcode 11 also, but after double checking it appears to only throw an error on xcode 12. Apologies for the incorrect information. Seems to only affect xcode 12.

**Comment by LucianoPAlmeida** [comment] 2020-08-20 23:26
@multinerd That being said I think the compiler was wrong before in accepting this, and now although is a change that breaks source compatibility, it is indeed a fact that this is ambiguous, at least in my opinion... because the compiler should not assume one or the other declaration in this case. I mean why would it select one of the overloads? there are no general rules for that. So to me, the ambiguous error is correct :) 

Since the properties are declared in different modules a possible way to disambiguate that is use declaration imports
```swift
import var SwifterSwift.UIView.shadowOffset // If you want the SwifterSwift one 
import var UIKit.UILabel.shadowOffset // If you want the UIKit one 
```
I think that could work ... but didn't test it

But if you think this worth a discussion and this is a source compat compiler regression, you can start a topic on [https://forums.swift.org](https://forums.swift.org) or open a JIRA ticket on [https://bugs.swift.org](https://bugs.swift.org)

**Comment by LucianoPAlmeida** [comment] 2020-08-21 00:02
Testing... seems like it doesn't work... :(

**Comment by Jayxiang** [comment] 2020-08-21 03:18
I have downloaded Xcode 12.0 beta 5 (12A8189h), it does report an error `Ambiguous use of 'shadowOffset'`.

Test: 
 if import SwifterSwift
```
            let viewLabel = testLabel as UIView
            viewLabel.shadowOffset = CGSize(width: 0, height: 4) 
```
It work for me.
Maybe the best way is to rename `UIView` extension...0.0

**Closed** 2020-08-31 14:20 UTC
Labels: confirmed bug: source, good first issue, help wanted
