### ISSUE TITLE
ambiguous use of foo

### ISSUE THREAD

**Issue by embassem** [SwifterSwift/SwifterSwift#455] opened 2018-04-18 20:58 UTC
> Please fill out this template when filing an issue.
>
> All comment lines beginning with an **>** instruct you with what info we expect. You can delete those lines once you've filled in the info.
>

[ ] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
 using an extension

### What did you expect to happen?
 to use  the extension for the lib i use

### What happened instead?
 it used the swifter swift extension 

### SwifterSwift Environment

- SwifterSwift version:4.1.1
- Xcode version:9.3
- macOS version running Xcode:10.13.3
- Swift version:4.1
- Platform(s) running SwifterSwift:iOS

### Demo Project
 i'm using DropDown[https://github.com/AssistoLab/DropDown] lib
and  i'm  try to change it's  width   , it's view had a  property width
```
let dropdown = Dropdown()
dropdown.width = 300
```
instead of change the with property it access the swifterSwift  extension 

also  this issue happened  when using  SwiftDate with SwifterSwift

**Comment by omaralbeik** [comment] 2018-04-18 21:11
Duplicate of [#176](https://github.com/SwifterSwift/SwifterSwift/issues/176)

**Comment by BennX** [comment] 2018-05-01 13:05
Looks like #174 helped since we haven't got any more comments on this. 

@embassem If there is anything else please reopen this issue or feel free to open a new issue.

**Closed by BennX** 2018-05-01 13:05 UTC
Labels: duplicate, won't support
