### ISSUE TITLE
[Proposal] wrap SwifterSwift extensions in a namespace?

### ISSUE THREAD

**Issue by shuoli84** [SwifterSwift/SwifterSwift#674] opened 2019-04-25 07:07 UTC
Now all extension method are exposed directly under extended type. e.g, UIView.cornerRadius. It is convenient in most time, but increased the possibility of name conflict. 

I just met the case

```swift
class MyButton: UIButton {
    var cornerRadius: CGFloat
}
```

Above code conflicts with 
```swift
UIView.cornerRadius // property defined in swifterswift UIViewExtensions
```

Maybe introduce a separate namespace like swifter, then 
```swift
view.swifter.cornerRadius // the one defined in swifterswift
```

**Comment by omaralbeik** [comment] 2019-04-25 08:13
Duplicate of #645

**Comment by shuoli84** [comment] 2019-04-25 14:04
@omaralbeik the original issue is closed and seems no further plan.
Subspec is not working in my case, I use UIKit subspec in the project.  So I renamed the property in my own code to avoid the conflict.

**Comment by shuoli84** [comment] 2019-04-25 14:06
But don't you see the catch? More extension we have, more chance we conflict with user's own code or other library. Which will leads the project to some sorrow situation. :P

**Comment by guykogus** [comment] 2019-04-25 14:13
Yes, we are aware. As you can see in #645 we had quite a long discussion about it, a bit offline as well. There are pros and cons to both solutions, and in the end we decided not to implement this change.

For now, in order to deal with conflict, either you'll have to change your project's code, or, if you have a clash from 2 separate libraries, you can use the solution recommended in #645: https://nshipster.com/import/

**Closed** 2019-04-26 02:39 UTC
Labels: duplicate
